CREATE TABLE DM_AP_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_AP_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM '/Users/Shriram/Desktop/clg_project/DATA_OUT/AP_CLG/part-00000-3b91b296-ab03-49a0-bc0c-f5493e50b927-c000.csv' DELIMITER ',' CSV HEADER;

ALTER TABLE DM_AP_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

