CREATE TABLE DM_AS_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_AS_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM
'/Users/Shriram/Desktop/clg_project/DATA_OUT/AS_CLG/part-00000-29822fb0-8966-49c8-8d4e-9b8a0bf89d0b-c000.csv' DELIMITER ',' CSV HEADER;

ALTER TABLE DM_AS_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

