CREATE TABLE DM_BR_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_BR_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 
'/Users/Shriram/Desktop/clg_project/DATA_OUT/BR_CLG/part-00000-45714c1b-4e8f-49cd-9b1a-a12e0c294107-c000.csv' DELIMITER ',' CSV HEADER;

ALTER TABLE DM_BR_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

