CREATE TABLE DM_CH_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_CH_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 
'/Users/Shriram/Desktop/clg_project/DATA_OUT/CH_CLG/part-00000-a3db94b7-d9c8-493c-9f65-d16347e8e2e9-c000.csv' DELIMITER ',' CSV HEADER;

ALTER TABLE DM_CH_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;


