CREATE TABLE DM_GA_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_GA_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 
'/Users/Shriram/Desktop/clg_project/DATA_OUT/GA_CLG/part-00000-ad568af3-3609-40e0-adef-986e7b5658bf-c000.csv' DELIMITER ',' CSV HEADER;

ALTER TABLE DM_GA_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

