CREATE TABLE DM_GJ_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_GJ_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 
'/Users/Shriram/Desktop/clg_project/DATA_OUT/GJ_CLG/part-00000-c0ddfbee-0271-4a5f-aeeb-9aad4be8f042-c000.csv' DELIMITER ',' CSV HEADER;

ALTER TABLE DM_GJ_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

