CREATE TABLE DM_HP_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_HP_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 
'/Users/Shriram/Desktop/clg_project/DATA_OUT/HP_CLG/part-00000-757a30a0-df37-43b1-9499-9b76ae094e76-c000.csv'
 DELIMITER ',' CSV HEADER;

ALTER TABLE DM_HP_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

