CREATE TABLE DM_JR_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_JR_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/JR_CLG/part-00000-452e69eb-4f8c-40e5-9a2b-0bae5b2302b6-c000.csv'
DELIMITER ',' CSV HEADER;

ALTER TABLE DM_JR_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

