CREATE TABLE DM_KA_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_KA_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/KA_CLG/part-00000-f2d78400-4c3d-40d2-bb87-838f76c72e7e-c000.csv'
 DELIMITER ',' CSV HEADER;

ALTER TABLE DM_KA_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

