CREATE TABLE DM_MANI_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_MANI_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/MANI_CLG/part-00000-bce56842-e807-44ea-bb8f-a9fa14aab604-c000.csv'
 DELIMITER ',' CSV HEADER;

ALTER TABLE DM_MANI_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

