CREATE TABLE DM_MEG_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_MEG_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/MEG_CLG/part-00000-21f6b200-76a0-48b2-bdd1-b43f472d0f2c-c000.csv'
DELIMITER ',' CSV HEADER;

ALTER TABLE DM_MEG_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

