CREATE TABLE DM_MH_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_MH_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 


'/Users/Shriram/Desktop/clg_project/DATA_OUT/MH_CLG/part-00000-e4f1f0c6-41c8-4e28-8f35-0c79f5fe7ac6-c000.csv'
DELIMITER ',' CSV HEADER;

ALTER TABLE DM_MH_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

