CREATE TABLE DM_MP_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_MP_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 


'/Users/Shriram/Desktop/clg_project/DATA_OUT/MP_CLG/part-00000-dd56b101-759f-471f-98b3-f11caa2baeee-c000.csv'
DELIMITER ',' CSV HEADER;

ALTER TABLE DM_MP_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

