CREATE TABLE DM_NAG_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_NAG_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM
 
'/Users/Shriram/Desktop/clg_project/DATA_OUT/NAG_CLG/part-00000-5fa4f9e4-f973-4b58-a40c-04a1630156a8-c000.csv'

  DELIMITER ',' CSV HEADER;

ALTER TABLE DM_NAG_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

