CREATE TABLE DM_PB_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_PB_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/PB_CLG/part-00000-a393e36f-7dcb-4595-9158-bf300eccb73f-c000.csv'

DELIMITER ',' CSV HEADER;

ALTER TABLE DM_PB_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

