CREATE TABLE DM_RJ_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_RJ_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/RJ_CLG/part-00000-f3ccef79-3bc7-4987-9aab-47a48ac27ce4-c000.csv'
DELIMITER ',' CSV HEADER;

ALTER TABLE DM_RJ_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

