CREATE TABLE DM_SK_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_SK_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 


'/Users/Shriram/Desktop/clg_project/DATA_OUT/SK_CLG/part-00000-c938e0ce-c12a-4596-b6af-3e00dad4780d-c000.csv'
DELIMITER ',' CSV HEADER;

ALTER TABLE DM_SK_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

