CREATE TABLE DM_TN_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_TN_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM '/Users/Shriram/Desktop/clg_project/DATA_OUT/TN_CLG/part-00000-a80c3222-7684-4480-ba33-2f65c97b88cd-c000.csv' DELIMITER ',' CSV HEADER;

ALTER TABLE public."DM_TN_CLG"
ADD COLUMN ID SERIAL PRIMARY KEY;

