CREATE TABLE DM_TR_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_TR_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/TR_CLG/part-00000-20557c14-75db-4e7c-b113-3411fbb35924-c000.csv'

DELIMITER ',' CSV HEADER;

ALTER TABLE DM_TR_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

