CREATE TABLE DM_UK_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_UK_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 

'/Users/Shriram/Desktop/clg_project/DATA_OUT/UK_CLG/part-00000-2e9226e4-c2b9-4544-9c25-7bff2bcddbe1-c000.csv'

 DELIMITER ',' CSV HEADER;

ALTER TABLE DM_UK_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

