CREATE TABLE DM_WB_CLG (
    CLG_NAME VARCHAR(255),
    RATING DECIMAL(3, 1),
    FEES INT,
    PKG INT,
    STATE VARCHAR(10),
    CLG_ID VARCHAR(10) 
);

COPY DM_WB_CLG(CLG_NAME, RATING, FEES, PKG, STATE, CLG_ID)
FROM 


'/Users/Shriram/Desktop/clg_project/DATA_OUT/WB_CLG/part-00000-37232043-d484-47ad-ae0e-58a9ff4e43e7-c000.csv'
DELIMITER ',' CSV HEADER;

ALTER TABLE DM_WB_CLG
ADD COLUMN ID SERIAL PRIMARY KEY;

